### ISSUE TITLE
请问是否支持mumu模拟器

### ISSUE THREAD

**Issue by haodedong** [Duckyal/Liaotu#1]

**Comment by Duckyal** [comment]
只适配了桌面端和雷电模拟器，如果你需要的话，可以借住op工具查找mumu模拟器窗口类名和窗口名，通过改源代码来实现mumu的适配

**Comment by Duckyal** [comment]
只适配了雷电模拟器和桌面端，如果你需要的话，可以借助op工具来查找mumu窗口名和窗口类名，以此修改源代码来适配mumu模拟器

**Comment by Duckyal** [comment]
只适配了桌面端，请耐心等待后续版本，或者参照op库（https://github.com/WallBreaker2/op）修改源代码

**Comment by Duckyal** [comment]
请于  https://github.com/Duckyal/Liaotu/releases/tag/v2.3  下载预发行使用
